version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 3000
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
